--DYNAMIC SQL
EXEC SP_EXECUTESQL N'SELECT * FROM EMP';

--TAKE EMPNO FROM USER
DECLARE @SQL_STATEMENT NVARCHAR(MAX)
DECLARE @ENO NVARCHAR(MAX)
SET @ENO='2'
SET @SQL_STATEMENT='SELECT * FROM EMP WHERE EMPNO='+@ENO
PRINT @SQL_STATEMENT
EXEC SP_EXECUTESQL @SQL_STATEMENT

--ANOTHER EXAMPLE
DECLARE @SQL NVARCHAR(MAX), @ATTRIBUTE NVARCHAR(MAX), @TABLE NVARCHAR(MAX), @DNO NVARCHAR(MAX);

SET @ATTRIBUTE = ' * ';
SET @TABLE = ' DEPT '
SET @DNO = '20';
SET @SQL = 'SELECT '  + @ATTRIBUTE + 'FROM ' +@TABLE + ' WHERE DEPTNO = ' + @DNO;

EXEC SP_EXECUTESQL @SQL

