--JOIN AND SUBQUERY ASSIGNMENT
SELECT * FROM Products
--1  LIST ALL THE PRODUCTS DETAILS WHOSE CATEGORY IS SAME AS 'TOFU'

SELECT * FROM PRODUCTS WHERE CATEGORYID IN(SELECT CATEGORYID FROM PRODUCTS WHERE PRODUCTNAME='TOFU')

--2  LIST ALL THE PRODUCTS DETAILS FOR THE CATEGORY 'BEVERAGES'
SELECT * FROM PRODUCTS WHERE CATEGORYID IN (SELECT CATEGORYID FROM CATEGORIES WHERE CATEGORYNAME='BEVERAGES')

--3  LIST ALL THE ORDERS PLACED BY THE COMPANY NAME "ISLAND TRADING"
SELECT * FROM ORDERS WHERE CUSTOMERID IN (SELECT CUSTOMERID FROM CUSTOMERS WHERE COMPANYNAME='ISLAND TRADING')

--4  LIST COMPANY NAME AND NO OF ORDER COUNT PLACED BY EACH COMPANY
SELECT C.COMPANYNAME,COUNT(O.CUSTOMERID)AS[NO OF COUNT] FROM CUSTOMERS C JOIN ORDERS O ON C.CUSTOMERID=O.CUSTOMERID GROUP BY C.COMPANYNAME

--5  LIST ORDERID, CUSTOMER_COMAPNAYNAME FOR ALL THE ORDERS WHICH ARE HANDLE BY THE EMPLOYEES WHOSE TITLE IS "SALES MANAGER"
SELECT EMPLOYEEID FROM EMPLOYEES WHERE TITLE='SALES MANAGER'
SELECT O.ORDERID,C.COMPANYNAME FROM CUSTOMERS C JOIN ORDERS O ON C.CUSTOMERID=O.CUSTOMERID WHERE O.EMPLOYEEID IN(SELECT EMPLOYEEID FROM EMPLOYEES WHERE TITLE='SALES MANAGER')
--6  LIST 3RD HIGHEST COSTLIEST PRODUCT
;WITH PRODUCTDATA AS(
SELECT *,DENSE_RANK() OVER(ORDER BY UNITPRICE)AS PRICE FROM PRODUCTS
)
SELECT * FROM PRODUCTDATA WHERE PRICE=3

--7  FOR THE PRODUCT TABLE DISPLAY PRODUCTNAME AND CATEGORYNAME. ARRANGE AS PER THE CATEGORYNAME
SELECT P.PRODUCTNAME,C.CATEGORYNAME FROM PRODUCTS P JOIN CATEGORIES C ON P.CATEGORYID=C.CATEGORYID ORDER BY C.CATEGORYNAME

--8  FOR THE ORDERS TABLE DISPLAY ORDERID CUSTOMER_COMPANYNAME AND EMPLOYEE_FULLNAME
SELECT O.ORDERID,C.COMPANYNAME,(E.FIRSTNAME+' '+E.LASTNAME)AS FULLNAME
FROM ORDERS O JOIN CUSTOMERS C ON O.CUSTOMERID=C.CUSTOMERID
JOIN EMPLOYEES E ON O.EMPLOYEEID=E.EMPLOYEEID

--9  LIST ORDERID, EMPLOYEE_FULLNAME, CUSTOMER_COMPANYNAME, CATEGORYNAME, SUPPLIER_COMPANYNAME, PRODUCTNAME, ORDERDETAIS_UNIRPRICE, ORDERDETAILS_QUANTITY , NETSTOCK
SELECT O.ORDERID,C.COMPANYNAME,(E.FIRSTNAME+' '+E.LASTNAME)AS FULLNAME,OD.UNITPRICE,OD.QUANTITY,P.PRODUCTNAME,P.UNITSINSTOCK,CAT.CATEGORYNAME,S.COMPANYNAME
FROM ORDERS O JOIN CUSTOMERS C ON O.CUSTOMERID=C.CUSTOMERID
JOIN EMPLOYEES E ON O.EMPLOYEEID=E.EMPLOYEEID
JOIN [ORDER DETAILS] OD ON OD.ORDERID=O.ORDERID
JOIN PRODUCTS P ON P.PRODUCTID=OD.PRODUCTID
JOIN CATEGORIES CAT ON CAT.CATEGORYID=P.CATEGORYID
JOIN SUPPLIERS S ON S.SUPPLIERID=P.SUPPLIERID

--10  LIST ALL THE ORDERS (ORDERID, PRODUCTNAME) PLACED BY THE CUSTOMER IN LONDON
SELECT O.ORDERID,P.PRODUCTNAME FROM ORDERS O
JOIN [ORDER DETAILS] OD ON OD.ORDERID=O.ORDERID
JOIN PRODUCTS P ON P.PRODUCTID=OD.PRODUCTID
WHERE O.CUSTOMERID IN (SELECT CUSTOMERID FROM CUSTOMERS WHERE CITY='LONDON')


--11  FOR THE COSTLIEST PRODUCT DISPLAY PRODUCTNAME, UNITPRICE, CATEGORYNAME, SUPPLIER_CONTACTNAME
SELECT P.PRODUCTNAME,P.UNITPRICE,C.CATEGORYNAME,S.CONTACTNAME FROM PRODUCTS P
JOIN CATEGORIES C ON C.CATEGORYID=P.CATEGORYID
JOIN SUPPLIERS S ON S.SUPPLIERID=P.SUPPLIERID
WHERE P.UNITPRICE IN (SELECT MAX(UNITPRICE) FROM PRODUCTS)

--12  LIST ALL THE PRODUCTNAME WHOSE ORDER PLACED IN MONTH OF AUGUST
SELECT PRODUCTNAME FROM PRODUCTS 
WHERE PRODUCTID IN(SELECT PRODUCTID FROM [ORDER DETAILS] 
WHERE ORDERID IN (SELECT ORDERID FROM ORDERS WHERE DATENAME(MM,ORDERDATE)='AUGUST'))

--13  LIST ORDERID, QUANTITY FOR ALL THE ORDERS. ASSIGNED RANK AS PER THE HIGHEST TO LOWEST QUANTITY. DO NOT MISS ANY NUMBER WHILE ASSIGNING THE RANK
SELECT DENSE_RANK()OVER(ORDER BY QUANTITY)AS RANK ,ORDERID,QUANTITY FROM [ORDER DETAILS]

--14 LIST ALL THE PRODUCTS FOR THE CATEGORY “DAIRY PRODUCT”
SELECT * FROM PRODUCTS WHERE CATEGORYID IN (SELECT CATEGORYID FROM CATEGORIES WHERE CATEGORYNAME='DAIRY PRODUCTS')

--15 LIST ALL THE PRODUCTS WHICH IS SUPPLIED BY THE COMPANY “BIGFOOT BREWERIES”  FOR THE CATEGORY “BEVERAGES”
SELECT *FROM PRODUCTS 
WHERE CATEGORYID IN (SELECT CATEGORYID FROM CATEGORIES WHERE CATEGORYNAME='BEVERAGES')
AND SUPPLIERID IN(SELECT SUPPLIERID FROM SUPPLIERS WHERE COMPANYNAME='BIGFOOT BREWERIES')

--16 PRINT   CATEGORYNAME , SUPPLIER COMAPNY NAME  AND PRODUCT COUNT FOR EACH CATEGORY AND SUPPLIER
SELECT C.CATEGORYNAME,S.COMPANYNAME,COUNT(PRODUCTID)AS PRODUCTCOUNT FROM PRODUCTS P
JOIN CATEGORIES C ON C.CATEGORYID=P.CATEGORYID
JOIN SUPPLIERS S ON S.SUPPLIERID=P.SUPPLIERID
GROUP BY C.CATEGORYNAME,S.COMPANYNAME
ORDER BY  C.CATEGORYNAME,S.COMPANYNAME

--17 PRINT REGION AND TERRITORYDESCRIPTION NAME IN ASCENDING ORDER
SELECT R.REGIONDESCRIPTION,T.TERRITORYDESCRIPTION FROM REGION R JOIN TERRITORIES T ON R.REGIONID=T.REGIONID
ORDER BY R.REGIONDESCRIPTION ,T.TERRITORYDESCRIPTION

--18 PRINT  EMPLOYEES NAME, REGION NAME, CITY AND COUNTRY  --(CHECK FOR THE ERROR,  NO REGION RELATIONSHIP)
SELECT FIRSTNAME+' '+LASTNAME,REGION,CITY,COUNTRY FROM EMPLOYEES

--19 FOR EACH CATEGORIES PRINT CATEGORYNAME AND SUPPLIERS NAME
SELECT C.CATEGORYNAME ,S.CONTACTNAME FROM PRODUCTS P
JOIN CATEGORIES C ON C.CATEGORYID=P.CATEGORYID
JOIN SUPPLIERS S ON S.SUPPLIERID=P.SUPPLIERID
GROUP BY C.CATEGORYNAME,S.CONTACTNAME

--20 PRINT EMPLOYEE TITLEOFCOURTESY, EMPLOYEE FIRST + LASTNAME , EMPLOYEE TITLE, MANAGER TITLEOFCURTASY, MANAGER FIRSTNAME + LASTNAME, MANAGER TITLE
SELECT E.TITLEOFCOURTESY,E.FIRSTNAME+' '+E.LASTNAME AS EMPFULLNAME,M.TITLEOFCOURTESY,M.FIRSTNAME+' '+M.LASTNAME AS MGRFULLNAME 
FROM EMPLOYEES E JOIN EMPLOYEES M ON E.REPORTSTO=M.EMPLOYEEID
